name: Purge Discord DMs

on:
  schedule:
    # Runs automatically every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-purge:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python delete_dms.py
 
